server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sharine
    username: testaccount
    password: testpassword
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  profiles:
    active: dev

qiniu:
  access-key: test
  secret-key: test
  bucket: sharine